-- Example analytics mart
CREATE OR REPLACE TABLE SUNNYBEST_ANALYTICS.MART_REVENUE_BY_CATEGORY AS
SELECT
  category,
  SUM(revenue) AS total_revenue
FROM SUNNYBEST_ANALYTICS.STG_SALES_ENRICHED
GROUP BY category;
